# prod_assistant/config/config_dev.yaml

app:
  name: pulseflow
  env: dev
  port: 8080

# -----------------------------------------------------------------
# Model Secrets Override
# -----------------------------------------------------------------
embedding:
  api_key: ${OPENAI_API_KEY}

llm:
  api_key: ${OPENAI_API_KEY}

# -----------------------------------------------------------------
# AstraDB Configuration
# -----------------------------------------------------------------
astra:
  api_endpoint: ${ASTRA_DB_API_ENDPOINT}
  keyspace: ${ASTRA_DB_KEYSPACE}
  token: ${ASTRA_DB_APPLICATION_TOKEN}
  collection_name: ${ASTRA_DB_COLLECTION}
