# prod_assistant/config/config_dev.yaml

app:
  name: pulseflow
  env: dev
  port: 8080

llm:
  provider: openai
  model: ${OPENAI_API_KEY}
  embedding_model: ${EMBED_MODEL}

astra:
  db_id: ${ASTRA_DB_ID}
  keyspace: ${ASTRA_DB_KEYSPACE}
  token: ${ASTRA_DB_APPLICATION_TOKEN}
