astra_db:
  collection_name: "pulseflow_data"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-large"

retriever:
  search_type: "similarity"
  top_k: 10
  fetch_k: 30
  lambda_mult: 0.5
  use_compression: false
  compression_type: "embeddings"
  similarity_threshold: 0.25

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
    provider: "openai"
    model_name: "gpt-4o"
    temperature: 0
    max_output_tokens: 2048
